# Generated by Django 3.2.5 on 2022-06-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rotation_options',
            new_name='Rotation_option',
        ),
    ]
